version: "3.9"

services:

  db:
    build: .
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    image: db:1.0
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
