version: "3.9"

services:

  backend:
    build: backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_INSTANCE_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWD=${MYSQL_PASSWORD}
      - FLASK_ENV
    image: backend:1.0

  db:
    build: db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    image: db:1.0
    volumes:
      - todos-data:/var/lib/mysql

  frontend:
    build: frontend
    depends_on:
      - backend
    image: frontend:1.0
    ports:
      - "80:80"

volumes:
  todos-data:
